project:
  type: book
  output-dir: docs

book:
  title: "linux"
  author: "Norah Jones"
  date: "12/30/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Sysadmin1.qmd
    - Sysadmin2.qmd
    - Sysadmin3.qmd
    - OpenShift1.qmd
    - OpenShift2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



